comp:
	g++ -c ./Include/FindNumber.cpp -I ./Headers -o ./Object/FindNumber.o 
	g++ -c ./Include/FindNumber_2.cpp -I ./Headers -o ./Object/FindNumber_2.o 
	

	g++ ./Apps/main.cpp ./Object/*.o -I ./Headers -o ./Bin/main.exe
run:
	./Bin/main.exe
main:
	g++ ./Apps/main.cpp ./Object/*.o -I ./Headers -o ./Bin/main.exe
Brain:
	g++ -c ./Include/Brain.cpp -I ./Headers -o ./Object/Brain.o 
Wait:
	g++ -c ./Include/FormatFunction.cpp -I ./Headers -o ./Object/FormatFunction.o 
	g++ -c ./Include/Brain.cpp -I ./Headers -o ./Object/Brain.o 
	g++ -c ./Include/Mouth.cpp -I ./Headers -o ./Object/Mouth.o 